---
title: "SITUACIÓN DE LA RED VIAL"
output: 
  flexdashboard::flex_dashboard:
    logo: data/logo.png
    horizontal_layout: scroll
    navbar:
       - { title: "Tableu:tipo de superficie", href: "https://public.tableau.com/views/RVN-Agosto2021/dash_RVN?%3Adisplay_static_image=y&%3AbootstrapWhenNotified=true&%3Aembed=true&%3Alanguage=es-ES&publish=yes&:embed=y&:showVizHome=n&:apiID=host0", align: right}
    theme : cerulean
   
---
<style>
.navbar-logo{
width:40px;
}
</style>

```{r}
library(leaflet)
library(tidyverse)
library(sf)
library(DT)
library(crosstalk)
library(mapview)
library(crosstalk)
library(plotly)
library(devtools)
library(htmlwidgets)
library(ggplot2)
library(RColorBrewer)
# Lectura de datos 
data <- st_read("data/RVN-2.gpkg",quiet = TRUE)
sp <- SharedData$new(data)

```

```{r}
 
```
Presentación
=========================================
Columna 1 
-----------------------------------------

### Sistema Nacional de Carreteras (SINAC) {data-height=320}

<p1> Se jerarquiza en las siguientes tres redes viales: Red Vial Nacional, Red Vial Departamental o Regional y Red Vial Vecinal o Rural</p1>

<p2>Red Vial Nacional.- Corresponde a las carreteras de interés nacional conformada por los **principales ejes longitudinales y transversales**, se constituye elemento receptor de las carreteras Departamentales o Regionales y de las carreteras Vecinales o Rurales según DS. Nº 017-2007-MTC, detallandose en <https://acortar.link/0PzM4u>.</p2>

```{r}
filter_select(
  id = "DEPARTAMEN",
  label = "Selecciona el departamento:",
  sharedData = sp,
  group = ~DEPARTAMEN  
)

```

### Mapa vial
```{r}
data %>% 
  mapview()
```

Columna 2
-----------------------------------------
### Estadística

```{r}
#ejemplo
#library(ggplot2)
#View(RVNP)
#ggplot(data=RVNP, aes(x=SUPERFIC))+
#geom_histogram()

#data("RVN-2.gpkg")
#p <- ggplot(RVN-2, aes(x = LONGITUD)) + geom_freqpoly()+ 
#scale_color_brewer(palette= "Set2")+ 
#theme_bw()
#ggplotly(p)


```


### Descarga en formato

```{r}
data %>% 
  st_set_geometry(NULL) %>%
  datatable(
    filter = "top",  
    extensions = c(
      "Buttons",  
      "Scroller"),
    rownames = FALSE, 
    class = "compact",
    width = "100%",
    options = list(
      dom = "Blrtip",
      deferRender = TRUE,
      scrollY = 300,
      scroller = TRUE,
      buttons = list(
        "excel",
        "csv")
      )
    )
```







